---
- hosts: local
  tasks:
    - name: install pre-requisites
      pip:
        name:
          - openshift
          - pyyaml
          - kubernetes
          - jmespath

    - name: Create a Frontend Deployment object from an inline definition
      environment:
          K8S_AUTH_KUBECONFIG: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG')}}"
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG')}}"
        definition: "{{ lookup('file', '../deployments/deployment.yaml')}}"

    - name: Create a Frontend service object
      environment:
          K8S_AUTH_KUBECONFIG: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG')}}"
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG')}}"
        definition: "{{ lookup('file', '../deployments/load-balancer.yaml')}}"
     
    - name: Create a Frontend Deployment object from an inline definition
      environment:
          K8S_AUTH_KUBECONFIG: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG')}}"
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG')}}"
        definition: "{{ lookup('file', '../deployments/backend-deployment.yaml')}}"

    - name: Create a Frontend service object
      environment:
          K8S_AUTH_KUBECONFIG: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG')}}"
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG')}}"
        definition: "{{ lookup('file', '../deployments/backend-service.yaml')}}"
#     - name: Get pod names
    - name: Get the pods in the default namespace
      environment:
          K8S_AUTH_KUBECONFIG: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG')}}"
      k8s_info:
        kind: Pod
        kubeconfig: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG')}}"
        namespace: default
      register: pod_list
      
    - name: Print pod names
      ansible.builtin.debug:
        msg: "{{ pod_list | community.general.json_query('resources[*].metadata.name' }}"
