---
- hosts: local
  tasks:
    - name: Pull Docker image
      docker_image:
        name: prathvirajbn/crowdcontract-frontend
        tag: latest
        source: pull
    
    # - name: Pull Docker image server
    #   docker_image:
    #     name: prathvirajbn/crowdcontract-backend
    #     tag: latest
    #     source: pull

#     - name: Create Docker container
#       shell: "docker run -d -p 80:80 prathvirajbn/crowdcontract-frontend"
    
    # - name: Create Docker container server
    #   shell: "docker run -d -p 4002:4002 prathvirajbn/server"
    
#     - name: Check for Python
#       raw: test -e /usr/bin/python
#       changed_when: false
#       failed_when: false
#       register: check_python
    
#     - name: Install Python
#       raw: apt -y update && apt install -y python
#       when: check_python.rc != 0
    - name: Ensure running application
      k8s_facts:
        namespace: sample
        kind: Pod
        label_selectors:
          - app=sample-v1-app
      register: pod_list
      until: pod_list.resources[0].status.phase == 'Running'
      delay: 10
      retries: 3

# For k8s
# python >= 3.6
# kubernetes >= 12.0.0
# PyYAML >= 3.11
# jsonpatch

