---
- hosts: local
  tasks:
#     - name: Pull Docker image
#       docker_image:
#         name: prathvirajbn/crowdcontract-frontend
#         tag: latest
#         source: pull
    
    - name: install pre-requisites
      pip:
        name:
          - openshift
          - pyyaml
          - kubernetes 

    - name: Create a Deployment object from an inline definition
      environment:
          K8S_AUTH_KUBECONFIG: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG')}}"
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG')}}"
        definition:
          kind: Deployment
          apiVersion: apps/v1
          metadata:
            name: crowdcontract-frontend
            namespace: default
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: crowdcontract-frontend
            template:
              metadata:
                labels:
                  app: crowdcontract-frontend
              spec:
                containers:
                - name: crowdcontract-frontend
                  image: prathvirajbn/crowdcontract-frontend:latest
                  env:
                  - name: DOCKER_DEFAULT_PLATFORM
                    value: "linux/amd64"
                  ports:
                  - containerPort: 80
                    targetPort: 3000
    - name: Create a service object
      environment:
          K8S_AUTH_KUBECONFIG: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG')}}"
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ lookup('env', 'K8S_AUTH_KUBECONFIG')}}"
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: load-balancer
            labels:
              app: crowdcontract-frontend
          spec:
            type: LoadBalancer
            ports:
            - port: 80
              targetPort: 80
              protocol: TCP
              nodePort: 31001
            selector:
              app: crowdcontract-frontend
# For k8s
# python >= 3.6
# kubernetes >= 12.0.0
# PyYAML >= 3.11
# jsonpatch
