# sudo ansible-playbook ansibleTest.yaml --ask-vault-pass --tags create_ec2
# AWS playbook
---

- name: launch ec2 instances for k8s worker nodes
  
  hosts: localhost
  become: false
  
  vars:
    key_name: ansiblekey
    region: us-east-1
    image: ami-007855ac798b5175e
    id: "web-app"
    sec_group: "{{ id }}-sec"
    ec2_access_key: "{{ lookup('env', 'ec2_access_key') }}"
    ec2_secret_key: "{{ lookup('env', 'ec2_secret_key') }}"
    keypair: aws-arth-key 
    instance_type: t2.micro
    image: ami-00bf4ae5a7909786c
    vpc_subnet_id: subnet-0f20d73e825bd2692
    security_group_id: sg-0344355829b3965a2
    region: ap-south-1
    output_dir: /home/devops/ansible-kubernetes-cluster-aws

  
  tasks:
    - name: Facts
      block:

      - name: Get instances facts
        ec2_instance_info:
          aws_access_key: "{{ec2_access_key}}"
          aws_secret_key: "{{ec2_secret_key}}"
          region: "{{ region }}"
          
        register: result

      - name: Instances ID
        debug:
          msg: "ID: {{ item.instance_id }} - State: {{ item.state.name }} - Public DNS: {{ item.public_dns_name }}"
        loop: "{{ result.instances }}"

      tags: always


    - name: launch ec2 instance
      amazon.aws.ec2:
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}"
        group_id: "{{ security_group_id }}"
        instance_type: "{{ instance_type }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        image: "{{ image }}"
        assign_public_ip: yes
        wait: yes
        wait_timeout: 500
        count: 3
        instance_tags:
          name: worker
          env: test
        region: "{{ region }}"
      register: worker_node_output

    - name: output of slave ec2 instance
      local_action:
        module: copy
        content: "{{ worker_node_output }}"
        dest: "{{ output_dir }}/worker_output" 