---
name: GitHub Actions for crowdContract
run-name: ${{ github.actor }} has started using GitHub Actions 🚀
on:
  push:
    branches:
      - main
jobs:
  build-frontend-push-img-to-Dockerhub:
    name: build dist for nginx container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: build frontend
        run: |
          cd client
          npm install
          npm run build
      - name: Archive /dist as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: client/dist
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: copy dist to . from Artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
        
      - uses: docker/build-push-action@v2
        with:
          context: client/
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/crowdcontract-frontend:latest
          push: ${{ github.ref == 'refs/heads/main' }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
